title: "Assistive Applications, Accessibility, and Disability Ethics (A3DE) at HRI 2024"
urltitle: "A3DE @ HRI24"
email: abhijat@cmu.edu
description: Assistive Applications, Accessibility, and Disability Ethics (A3DE) workshop at HRI 2024
keywords: hri, workshop, robotics, disability, accessibility, assistance



baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']

# Google Analytics
