title: "Assistive Applications, Accessibility, and Disability Ethics (A3DE) at HRI 2024"
urltitle: "A3DE @ HRI24"
email: reuben.aronson@tufts.edu
description: Assistive Applications, Accessibility, and Disability Ethics (A3DE) workshop at HRI 2024
keywords: hri, workshop, robotics, disability, accessibility, assistance



baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']

# What sections are available?
sections:
  call: true
  dates: true
  schedule: false
  speakers: true

