title: "All Things Attention: Bridging Different Perspectives on Attention"
urltitle: "All Things Attention"
email: abhijat@cmu.edu
description: All Things Attention NeurIPS workshop
keywords: neurips, attention, workshop, computer vision, robotics, machine learning, gaze, interaction, neuroscience, cognitive psychology



baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']

# Google Analytics
